```{r}
library(readr)
library(ggplot2)
library(patchwork)
library(purrr)
library(dplyr)
library(tidyr)
library(igraph)
library(stringr)
library(viridis)
```

```{r}
#Get common and cell type specific TF->target_gene interactions

get_common_spec_nets <- function(tb){
  ctype_edges <- map(tb$fname, read_csv)
  ctype_nets <- map(ctype_edges, graph_from_data_frame, directed = TRUE)
  names(ctype_nets) <- tb$ctype
  
  net_inter <- igraph::intersection(ctype_nets$Epiblast, 
                                    ctype_nets$PE, 
                                    ctype_nets$TE, 
                                    keep.all.vertices = FALSE)
  
  epi_specific <- difference(ctype_nets$Epiblast, ctype_nets$PE) %>% 
    difference(ctype_nets$TE) %>% 
    delete_vertices(v = degree(.) == 0)
  
  pe_specific <- difference(ctype_nets$PE, ctype_nets$Epiblast) %>% 
    difference(ctype_nets$TE) %>% 
    delete_vertices(v = degree(.) == 0)
  
  te_specific <- difference(ctype_nets$TE, ctype_nets$Epiblast) %>% 
    difference(ctype_nets$PE) %>% 
    delete_vertices(v = degree(.) == 0)
  return(list(common = net_inter, 
              epi = epi_specific, pe = pe_specific, te = te_specific))
}
```

```{r}
#Find the number of edges from the marker of interest to target genes (out_degree)

get_mrk_activity <- function(net, cell_type, mrks, method, normalisation){
  net_edg <- igraph::as_data_frame(net) %>% 
    group_by(from) %>% 
    summarise(out_deg = n()) %>%
    mutate(norm_outdeg = out_deg/mean(degree(tmp$epi, mode = "out")[degree(tmp$epi, mode = "out")>0], trim = 0.25)) %>% #Normalize the out degree by using the mean of out degrees within the IQR
    #filter(from %in% mrks) %>% 
    select(from, out_deg, norm_outdeg) %>% 
    mutate(ctype = cell_type, method = method, normalisation = normalisation)
  missing_mrks <- setdiff(mrks, net_edg$from)
  if(length(missing_mrks) > 0){
    net_edg <- bind_rows(net_edg, 
                         tibble(from = missing_mrks, out_deg = 0, norm_outdeg = 0,
                                ctype = cell_type, method = method, 
                                normalisation = normalisation))
  }
  
  return(net_edg)
}
```

```{r}
Get_mrk_of_interest <- function(Activity_list, mrk_of_interest)
{
  Activity_mrk_of_interest <- Activity_list[Activity_list$from %in% mrk_of_interest,]
  return(Activity_mrk_of_interest)
}
```

```{r}
dpath <- "/path/to/GRN/inference/tables/"

tb_files <- list.files(dpath, pattern = "\\.csv$")
#tb_files <- list.files(dpath)

tb_details <- sapply(strsplit(tb_files, split = "[.]"), `[`, 1)
tb_details <- strsplit(tb_details, split = "_")

tb_details <- map_dfr(tb_details, 
                      function(x) tibble(method = x[1],
                                         normal = x[2],
                                         ctype = x[3])) %>% 
  mutate(fname = paste0(dpath, tb_files),
         method = str_replace(method, "TFnet", ""),
         method = str_replace(method, "res", ""),
         method = str_replace(method, "Res", "")) %>% 
  nest(data = c(ctype, fname)) %>% 
  filter(!grepl("Imp", method))
```

```{r}
mrk_of_interest <- c("CDX2", "GATA4", "NANOG")
```

```{r}
activity_list <- vector("list", nrow(tb_details))

for(i in 1:nrow(tb_details)){
  print(i)
  tmp <- get_common_spec_nets(tb_details$data[[i]])
  tmp_activities <- map2(tmp, names(tmp), get_mrk_activity, 
                         mrks = mrk_of_interest, method = tb_details$method[i],
                         normalisation = tb_details$normal[i])
  
  
  activity_list[[i]] <- bind_rows(tmp_activities) 
    # mutate(norm_odeg = norm_outdeg/max(norm_outdeg))
    # mutate(sqrt_odeg = sqrt(out_deg)) %>% 
    # mutate(norm_odeg = sqrt_odeg/max(sqrt_odeg))
}
```

```{r}
activity_list_mrk <- map(activity_list, Get_mrk_of_interest, mrk_of_interest = mrk_of_interest)

activity_results <- bind_rows(activity_list_mrk) %>% 
  mutate(method = case_when(
    method == "0cor" ~ "Spearman",
    method == "0GENIE3" ~ "GENIE3",
    method == "0L0L2" ~ "L0L2",
    method == "0MI" ~ "MI",
    method == "Cor" ~ "Spearman+CA",
    method == "GENIE3" ~ "GENIE3+CA",
    method == "L0L2" ~ "L0L2+CA",
    method == "MI" ~ "MI+CA"
  ),
  ctype = str_to_upper(ctype),
  normalisation = case_when(
    normalisation == "bc" ~ "Batch-corrected",
    normalisation == "fpkm" ~ "FPKM",
    normalisation == "lc" ~ "log-counts",
    normalisation == "tpm" ~ "TPM")
  ) %>% 
  mutate(method = factor(method, 
                         levels = c("L0L2", "GENIE3", "Spearman", "MI",
                                    "L0L2+CA", "GENIE3+CA", "Spearman+CA", "MI+CA"),
                         ordered = TRUE),
         normalisation = factor(normalisation, 
                                levels = c("log-counts", "Batch-corrected", 
                                           "FPKM", "TPM"),
                                ordered = TRUE),
         actv = norm_outdeg >= (quantile(norm_outdeg)["75%"]-0.005)) # actv TRUE if normalized out-degree larger than 75% percentile
```

```{r}
# Build heatmap for each Cell type-Normalisation group

ctypes <- unique(activity_results$ctype)
norms <- levels(activity_results$normalisation)

p_activ <- vector("list", length(ctypes)*length(norms))
k <- 1

activity_results$from = factor(activity_results$from, levels = mrk_of_interest)

for(i in seq_along(ctypes)){
  for(j in seq_along(norms)){
    p_activ[[k]] <- activity_results %>% 
      filter(ctype == ctypes[i] & normalisation == norms[j]) %>% 
      ggplot(aes(method, from, fill = as.numeric(actv))) +
      geom_tile() +
      scale_x_discrete(guide = guide_axis(angle = 90)) +
      scale_fill_viridis(limits = c(0, 1)) +
      labs(x = "", y = "", fill = "Active or Inactive",
           title = paste0(ctypes[i], " ", norms[j]), size = 1) +
      theme(axis.text=element_text(size=12),
        axis.title=element_text(size=10), 
        plot.title = element_text(size=8,face="bold"),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()
        #axis.text.y=element_blank(),
        #axis.ticks.y=element_blank(),
        #plot.title = element_blank()
        )
    
    k <- k + 1
  }
}

p_activ_grid <- wrap_plots(p_activ, nrow = 4, ncol = 4) + 
  plot_layout(guides = "collect") 

ggsave(filename = paste0("figs/mrk_heatmap_YESNO_v2_T1.svg"), 
       plot = p_activ_grid, width = 300, height = 180, units = "mm")
```

```{r}
# Build barchart for each Cell type-Normalisation group

Normalisation_seq <- c('TPM', 'FPKM', 'log-counts', 'Batch-corrected')
Method_seq <- c('L0L2', 'L0L2+CA', 'GENIE3', 'GENIE3+CA', 'Spearman', 'Spearman+CA', 'MI', 'MI+CA')
Ctype_seq <- c('COMMON', 'EPI', 'PE', 'TE')

activity_results$from <- factor(activity_results$from, levels = c('NANOG', 'GATA4', 'CDX2'))

for (Norm in Normalisation_seq)
{
  
  Bar_charts <- vector("list", length(Method_seq)*length(Ctype_seq))
  Count <- 1
  
  for (Method in Method_seq)
  {
    
    activity_results_norm_method <- filter(activity_results, normalisation == Norm & method == Method)
    Y_max <- max(activity_results_norm_method$out_deg) + 10
    
    for (Ctype in Ctype_seq)
    {
      Bar_charts[[Count]] <- activity_results %>% filter(normalisation == Norm & method == Method & ctype == Ctype) %>% 
        ggplot(aes(x = from, y = out_deg)) + ylim(0, Y_max) + theme_bw() + theme(axis.text.x=element_blank(), 
                                                                                 axis.title=element_blank(),
                                                                                 axis.text.y=element_text(size=13))
      
      if (Ctype == 'EPI')
      {
        Bar_charts[[Count]] <- Bar_charts[[Count]] + geom_bar(stat = 'identity', fill = '#009c00')
      }
      else if (Ctype == 'PE')
      {
        Bar_charts[[Count]] <- Bar_charts[[Count]] + geom_bar(stat = 'identity', fill = '#ff284b')
      }
      else if (Ctype == 'TE')
      {
        Bar_charts[[Count]] <- Bar_charts[[Count]] + geom_bar(stat = 'identity', fill = '#287dff')
      }
      else
      {
         Bar_charts[[Count]] <- Bar_charts[[Count]] + geom_bar(stat = 'identity')
      }
      
      Count <- Count + 1
    }
  }
  
  Bar_charts_multi <- wrap_plots(Bar_charts, nrow = length(Method_seq), ncol = length(Ctype_seq)) + 
  plot_layout(guides = "collect") 
  
  ggsave(filename = paste0("figs/Bar_charts_multi_", Norm,  ".svg", sep = ""), 
       plot = Bar_charts_multi, width = 300, height = 500, units = "mm")

}
```



