```{r}
rm(list=ls())
```

```{r}
library(readr)
library(dplyr)
library(igraph)
library(visNetwork)
library(epitools)
```

```{r}
load("data/sce_integrated_lateBlast_clean.RData") #single cell expression data from human pre-implantation blastocyst
tfs <- read_tsv("data/Homo_sapiens_TF.txt") #a list of human TFs
Human_Genelist <- read_csv('data/Human_genelist.csv')
```


```{r}
#Get TFs from the Human_Genelist
Human_Genelist_TFs <- filter(Human_Genelist, `Is TF?` == 'Yes')
```


```{r}
#For Spearman rank correlation test
Correlation_test <- function(TF_Y_expression){
  TF_Correlation <- cor.test(TF_expression[i, ], TF_Y_expression,  method = "spearman", exact=FALSE)
  TF_Correlation_estimate <- TF_Correlation$estimate
  
  # If p value larger than 0.1, set the Spearman correlation score (TF_Correlation_estimate) to 0
  if (TF_Correlation$p.value >= 0.05){
    TF_Correlation_estimate <- 0
  }
  
  return(TF_Correlation_estimate)
}
```

```{r}
cell_type_seq <- c('Epiblast', 'PE', 'TE')
#cell_type_seq <- c('Epiblast')

for (ctype in cell_type_seq)
{
  dpath <- paste0("data/TFnetMIres_tpm_", ctype, ".csv") #Path for GRN table
  grn_tb <- read_csv(dpath)
  
  #Get GRN of TFs
  grn_tb_TFs <- filter(grn_tb, FROM %in% Human_Genelist_TFs$`HGNC symbol` & TO %in% Human_Genelist_TFs$`HGNC symbol`)
  
  #Get SCE object of epiblast cells
  if (ctype == "Epiblast"){
    sce_cell_type <- "Epiblast"
  } else if (ctype == "PE"){
    sce_cell_type <- "Primitive endoderm"
  } else if (ctype == "TE"){
    sce_cell_type <- "Trophectoderm"
  }
       
  sce_Data <- sce[ ,sce$cell_type == sce_cell_type]
  
  #Get all the expressed TFs in the sce_Epiblast
  Expressed_TFs <- Human_Genelist_TFs$`HGNC symbol` %in% rownames(sce_Data@assays@data@listData$tpm)
  Expressed_TFs <- Human_Genelist_TFs$`HGNC symbol`[Expressed_TFs]
  
  #Get TPM of all the expressed TFs in epiblast cells
  All_TF_expression <- sce_Data@assays@data@listData$tpm[Expressed_TFs, ]
  
  All_TF_expression_mean <- apply(All_TF_expression, MARGIN = 1, mean)
  All_TF_expression_lower_quartile <- as.vector(quantile(All_TF_expression_mean, probs = seq(0, 1, 1/4))['25%'])
  #All_TF_expression_lower_quartile <- All_TF_expression_mean[All_TF_expression_mean<All_TF_expression_lower_quartile]
  #All_TF_expression_lower_quartile_mean <- max(All_TF_expression_lower_quartile)
  
  TFs_to_plot <- filter(grn_tb, FROM %in% Expressed_TFs & TO %in% Expressed_TFs)
  TFs_to_plot <- unique(c(unique(TFs_to_plot$FROM), unique(TFs_to_plot$TO)))
  
  #TFs_to_plot <- 'AIRE'
  
  
  #Plot targets, regulators and feedback networks for all the TFs expressed
  fig_dir <- paste0('figs/GRN_plots_v5.1/', ctype, '_GRN_pval_0.05_v5.1/')
  #fig_dir <- 'figs/Test_plots/'
  
  Network_types <- c('Target_network', 'Regulator_network', 'Feedback_network')
  
  Activation_edges_color <- "#00A300"
  Repression_edges_color <- "#FF0063"
  Insignificant_edges_color <- "#000000"
  Vertices_color <- "#EAF6F6"
  
  Plot_number <- 0
  
  for (TF in TFs_to_plot)
  #for (TF in TFs_to_plot[1:5])
  {
  
    for (Network in Network_types)
    {
      Plot_number <- Plot_number+1
      Total_plot_number <- as.character(length(TFs_to_plot)*length(Network_types))
      print(paste('Plotting ', Network, ' for ', TF, ' in ', ctype, ' --- ', as.character(Plot_number), '/', Total_plot_number, sep = ''))
      
      TF_of_interest <- TF
      Number_of_nodes <- 25
      
      TFs_to_exclude <- c()
      Keep_looping <- T
      
      #This while loop will keep looping to update the TFs_to_exclude list until no new TF is added to this list
      #Also remove TF nodes from the network if the TF is in the TFs_to_exclude list
      #TFs_to_exclude are TFs that are below certain expression threshold but still shown as insignificant or positive interactors (either targets or regulators) of the TF_of_interest
      while (Keep_looping)
      {
      
        if (Network == 'Target_network' | Network == 'Feedback_network')
        {
        
          #Get all targets of the TF_of_interest
          grn_tb_targets <- filter(grn_tb_TFs, FROM %in% TF_of_interest & !TO %in% TFs_to_exclude)
          grn_tb_targets <- arrange(grn_tb_targets, desc(SCORE))
          
          #Pick the top 25 targets
          if(nrow(grn_tb_targets) < Number_of_nodes) 
          {
            grn_tb_targets_Top <- grn_tb_targets
          } else
          {
            grn_tb_targets_Top <- grn_tb_targets[1:Number_of_nodes, ]
          }
          
          Top_targets <- grn_tb_targets_Top$TO
          
          #Get targets of targets network
          targets_of_targets <- filter(grn_tb_TFs, FROM %in% Top_targets & TO %in% c(Top_targets, TF_of_interest))
          
          #Combined the core network and the targets of targets network to build the final network
          grn_tb_Top_network <- rbind(grn_tb_targets_Top, targets_of_targets)
        
        }
        
        if (Network == 'Regulator_network' | Network == 'Feedback_network')
        {
          
          #Get all regulators of the TF_of_interest
          grn_tb_regulators <- filter(grn_tb_TFs, TO %in% TF_of_interest & !FROM %in% TFs_to_exclude)
          grn_tb_regulators <- arrange(grn_tb_regulators, desc(SCORE))
          
          if(nrow(grn_tb_regulators) < Number_of_nodes) 
          {
            grn_tb_regulators_Top <- grn_tb_regulators
          } else
          {
            grn_tb_regulators_Top <- grn_tb_regulators[1:Number_of_nodes, ]
          }
          
          Top_regulators <- grn_tb_regulators_Top$FROM
          
          targets_of_regulators <- filter(grn_tb_TFs, FROM %in% c(Top_regulators, TF_of_interest) & TO %in% Top_regulators)
          
          grn_tb_Top_network <- rbind(grn_tb_regulators_Top, targets_of_regulators)
          
        }
        
        
        
        if (Network == 'Feedback_network')
        {
          
          #Get network of targets if the targets are the regulators of the regulators of the TF_of_interest (Which create a feedback loop)
          target_is_regulator_of_regulator <- filter(grn_tb_TFs, FROM %in% Top_targets & TO %in% Top_regulators)
          #regulator_is_regulator_of_target <- filter(grn_tb_TFs, FROM %in% Top_regulators & TO %in% Top_targets)
          Core_network_out <- filter(grn_tb_TFs, FROM %in% TF_of_interest & TO %in% target_is_regulator_of_regulator$FROM)
          Core_network_in <- filter(grn_tb_TFs, FROM %in% target_is_regulator_of_regulator$TO & TO %in% TF_of_interest)
          
          grn_tb_Top_network <- rbind(target_is_regulator_of_regulator, 
                                              #regulator_is_regulator_of_target, 
                                              Core_network_out, 
                                              Core_network_in)
          
        }
        
        if (nrow(grn_tb_Top_network) > 0)
        {
        
          tf_tf <- graph_from_data_frame(grn_tb_Top_network, directed = TRUE)
          
          #Calculate log2(TPM+1)
          TF_expression <- All_TF_expression[V(tf_tf)$name, ]
          TF_expression_mean <- apply(TF_expression, MARGIN = 1, mean)
          TF_expression_LogMeanScaled <- log2(TF_expression_mean+1)*2
          
  
          #Run the correlation test on the top X nodes
          TF_Correlation_matrix <- c()
          
          for (i in rownames(TF_expression)){
            TF_Correlation <- apply(TF_expression, MARGIN = 1, Correlation_test)
            TF_Correlation_matrix <- rbind(TF_Correlation_matrix, TF_Correlation) # combine correlation test results to create a matrix
          }
            
          rownames(TF_Correlation_matrix) <- rownames(TF_expression)
            
          
          #Get all negatively correlated interactions
          Repression_edges_combined <- c()
          Insignificant_edges_combined <- c()
            
          for (i in rownames(TF_Correlation_matrix)){
            
            Negative_relation_targets <- names(TF_Correlation_matrix[,i][TF_Correlation_matrix[,i]<0]) # Get names of target TFs that has negative correlation with the regulator TF
            Insignificant_targets <- names(TF_Correlation_matrix[,i][TF_Correlation_matrix[,i]==0])
            
            if (length(Negative_relation_targets) > 0)
            {
              Repression_edges <- as.matrix(data.frame(i,Negative_relation_targets)) # Make a regulator->target pairwise matrix for negatively correlated targets of the regulator
              Repression_edges_combined <- rbind(Repression_edges_combined, Repression_edges)
            }
            
            if (length(Insignificant_targets) > 0)
            {
              Insignificant_edges <- as.matrix(data.frame(i,Insignificant_targets)) 
              Insignificant_edges_combined <- rbind(Insignificant_edges_combined, Insignificant_edges)
            }
          
          }
          
          #Find TFs_to_exclude here
          #TFs_to_exclude are positive or insignificant interactors (either regulators or targets) of TF_of_interest and below All_TF_expression_lower_quartile
          Positive_relation_ToI_interactors <- names(TF_Correlation_matrix[,TF_of_interest][TF_Correlation_matrix[,TF_of_interest]>0])
          Insignificant_relation_ToI_interactors <- names(TF_Correlation_matrix[,TF_of_interest][TF_Correlation_matrix[,TF_of_interest]==0])
          Interactors_to_check <- c(Positive_relation_ToI_interactors, Insignificant_relation_ToI_interactors)
          Interactors_to_check <- Interactors_to_check[!Interactors_to_check %in% TF_of_interest]
          
          TFs_to_exclude_new <- names(TF_expression_mean[Interactors_to_check][TF_expression_mean[Interactors_to_check] < All_TF_expression_lower_quartile])
          TFs_to_exclude <- c(TFs_to_exclude, TFs_to_exclude_new)
          # If no TFs_to_exclude_new, set Keep_looping to FALSE and stop the while loop next round
          if (identical(TFs_to_exclude_new, character(0)))
          {
            Keep_looping <- F
            
            # So will not plot networks for central TF expression below threshold
            if (as.numeric(TF_expression_mean[TF_of_interest]) > All_TF_expression_lower_quartile)
            {
              #Plot graphs
              V(tf_tf)$shape <- "circle"
              E(tf_tf)$value <- E(tf_tf)$SCORE/0.5
              E(tf_tf)$width<-E(tf_tf)$SCORE/0.5
              V(tf_tf)$size<-TF_expression_LogMeanScaled
              V(tf_tf)$label<-V(tf_tf)$name
              V(tf_tf)$label.cex<-0.8
              V(tf_tf)$label.family<-"Times"
              V(tf_tf)$label.color<-"black"
              V(tf_tf)$color<-Vertices_color
              E(tf_tf)$color<-adjustcolor(Activation_edges_color, alpha.f = 0.5)
              E(tf_tf)$curved<-0.2
              
              
              if (!is.null(Repression_edges_combined))
              {
                Repression_edges_combined <- as.vector(t(Repression_edges_combined))
                Repression_edges_IDs <- get.edge.ids(tf_tf, Repression_edges_combined) #Get IDs of the edges that have negative correlation
                E(tf_tf)[Repression_edges_IDs]$color<-adjustcolor(Repression_edges_color, alpha.f = 0.8) #Color negative correlated edges by red
              }
              
              if (!is.null(Insignificant_edges_combined))
              {
                Insignificant_edges_combined <- as.vector(t(Insignificant_edges_combined))
                Insignificant_edges_IDs <- get.edge.ids(tf_tf, Insignificant_edges_combined) 
                E(tf_tf)[Insignificant_edges_IDs]$color<-adjustcolor(Insignificant_edges_color, alpha.f = 0.3) 
              }
              
              #-----Legends for vertices----#
              Vsize_min <- floor(min(V(tf_tf)$size)*10)/10
              Vsize_max <- ceiling(max(V(tf_tf)$size)*10)/10
              Num_of_level_V <- 5
              Legend_interval_V <- (Vsize_max - Vsize_min)/(Num_of_level_V-1)
              Vsize_max_adjust <- Vsize_min + Legend_interval_V*Num_of_level_V
              Legend_levels_V <- seq(Vsize_min, Vsize_max_adjust, Legend_interval_V)[1:Num_of_level_V]
              Legend_levels_V <- round(Legend_levels_V, digits = 1)
              #-----Legends for vertices----#
              
              
              #-----Legends for edges----#
              Esize_min <- floor(min(E(tf_tf)$width)*10)/10
              Esize_max <- ceiling(max(E(tf_tf)$width)*10)/10
              Num_of_level_E <- 5
              Legend_interval_E <- (Esize_max - Esize_min)/(Num_of_level_E-1)
              Esize_max_adjust <- Esize_min + Legend_interval_E*Num_of_level_E
              Legend_levels_E <- seq(Esize_min, Esize_max_adjust, Legend_interval_E)[1:Num_of_level_E]
              Legend_levels_E <- round(Legend_levels_E, digits = 1)
              #-----Legends for edges----#
              
              
              pdf(file=paste(fig_dir, Network, '_of_', TF, '.pdf', sep = ''),width=10,height=10,useDingbats=F);
              {
                #net.graphopt <- layout_with_graphopt(tf_tf, charge = 0.009, mass = 50, spring.length = E(tf_tf)$weight)
                plot.igraph(tf_tf, edge.arrow.width = 2)#, layout = net.graphopt)
                
                legend(-1.4,1.25,legend=levels(as.factor(Legend_levels_V)),pt.cex=Legend_levels_V/2.5, col='black', pt.bg="#EAF6F6", pch = 21, title = as.expression(bquote(bold('Mean Expression\n(log2(TPM+1))'))), cex = 0.9, bty = 'n')
                legend(-1.0,1.25,legend=levels(as.factor(Legend_levels_E)), col='black', lty = 1, lwd=Legend_levels_E, title = as.expression(bquote(bold('MI Score\n(-log10(p))'))), cex = 0.9, bty = 'n')
                legend(-0.7,1.3,legend=levels(factor(c('Activation', 'Repression', 'Insignificant correlation'), levels = c('Correlated', 'Anti-correlated', 'Uncorrelated'))), title = as.expression(bquote(bold('Spearman Correlation'))), col=c(Activation_edges_color, Repression_edges_color, Insignificant_edges_color), lty = 1, lwd = 2, cex = 0.9, bty = 'n')
              }
              dev.off()
            }
            
          }
            
          
          # V(tf_tf)$shape <- "dot"
          # GRN_plot <- visIgraph(tf_tf) %>% visNodes(scaling = TF_expression_LogMeanScaled)# %>% visEdges(color = E(tf_tf)$color)
          # visSave(GRN_plot, file = "figs/GRN_plot_test2.html", background = "white")
          
        } else
        {
          print(paste(TF, ' has no ', Network, sep = ''))
          # If no network can be constructed for the TF_of_interest, also stop looping.
          Keep_looping <- F
        }
        
      }
    
    }
  
  }
}
```
```{r}
grn_tb_TFs
```


